source setvars
$REXEC CMD BATCH --vanilla "--args GSE11237 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE11237_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE12225 $DATAHOME GPL3676" $SRCHOME/gse_PROCESSED.R $LOG/GSE12225-GPL3676_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE12945 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE12945_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE13067 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE13067_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE13294 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE13294_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE14095 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE14095_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE14333 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE14333_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE16125 $DATAHOME GPL5175" $SRCHOME/gse_PROCESSED.R $LOG/GSE16125-GPL5175_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE17536 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE17536_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE17537 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE17537_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE17538 $DATAHOME GPL570" $SRCHOME/gse_PROCESSED.R $LOG/GSE17538-GPL570_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE18105 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE18105_downloadPROCESSED.log
#$REXEC CMD BATCH --vanilla "--args GSE2109 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE2109_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE21510 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE21510_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE21815 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE21815_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE24549 $DATAHOME GPL5175" $SRCHOME/gse_PROCESSED.R $LOG/GSE24549-GPL5175_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE24550 $DATAHOME GPL5175" $SRCHOME/gse_PROCESSED.R $LOG/GSE24550-GPL5715_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE2630 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE2630_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE26682 $DATAHOME GPL96" $SRCHOME/gse_PROCESSED.R $LOG/GSE26682-GPL96_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE26682 $DATAHOME GPL570" $SRCHOME/gse_PROCESSED.R $LOG/GSE26682-GPL570_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE26906 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE26906_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE27544 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE27544_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE28702 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE28702_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE3294 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE3294_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE33113 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE33113_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE39582 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE39582_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE3964 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE3964_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE4045 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE4045_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE4526 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE4526_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE45270 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE45270_downloadPROCESSED.log

./download_TCGA.sh
./download_TCGA-rectum.sh
./download_TCGA-RNASeqV2.sh
./download_TCGA-RNASeqV2-rectum.sh
